# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
# 
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "test"
env.CARGO_TERM_COLOR = "always"

[jobs.test]
command = ["gleam", "test"]
need_stdout = true
default_watch = false
extraneous_args = false
watch = ["./src", "./test"]
