# This is a configuration file for the bacon tool
#
# Complete help on configuration: https://dystroy.org/bacon/config/
#
# You may check the current default at
#   https://github.com/Canop/bacon/blob/main/defaults/default-bacon.toml

default_job = "nextest"
env.CARGO_TERM_COLOR = "always"

[jobs.e2etest]
command = ["playwright", "test", "-c", "end2end/playwright.config.ts"]
need_stdout = true
background = false
default_watch = true
watch = ["end2end/tests"]

[exports.locations]
auto = true
path = ".bacon-locations"
line_format = "{kind} {path}:{line}:{column} {message}"
